[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]
itertools = "0.14.0"
fancy-regex = "0.16.2"
rayon = "1.11.0"
colored = "3.0.0"
